global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/REPLACE_WITH_ACTUAL_SLACK_WEBHOOK_URL'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password' # Replace with actual password or use secrets management

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-mlops'
  routes:
  - match:
      severity: critical
    receiver: 'team-mlops-pager'
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'team-mlops'
    repeat_interval: 3h

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

receivers:
- name: 'team-mlops'
  slack_configs:
  - channel: '#mlops-alerts'
    title: "{{ .GroupLabels.alertname }} - {{ .Status | toUpper }}"
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Instance:* {{ .Labels.instance }}
        {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
      {{ end }}
    send_resolved: true
  email_configs:
  - to: 'mlops-team@example.com'
    send_resolved: true

- name: 'team-mlops-pager'
  slack_configs:
  - channel: '#mlops-critical'
    title: "🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }} - {{ .Status | toUpper }}"
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Description:* {{ .Annotations.description }}
        *Severity:* {{ .Labels.severity }}
        *Instance:* {{ .Labels.instance }}
        {{ if .Annotations.runbook_url }}*Runbook:* {{ .Annotations.runbook_url }}{{ end }}
      {{ end }}
    send_resolved: true
  pagerduty_configs:
  - service_key: 'replace_with_pagerduty_service_key'
    send_resolved: true
  email_configs:
  - to: 'oncall-mlops@example.com'
    send_resolved: true