apiVersion: v1
kind: ConfigMap
metadata:
  name: gliner-config
  namespace: mlops
  labels:
    app: gliner-api
data:
  MODEL_NAME: "urchade/gliner_medium-v2.1"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  API_KEY_ENABLED: "true"
  PROJECT_NAME: "GLiNER-MLOps"
  METRICS_ENABLED: "true"
  STORAGE_TYPE: "s3"
  S3_BUCKET_NAME: "gliner-models"
  AWS_REGION: "us-west-2"
---
apiVersion: v1
kind: Secret
metadata:
  name: gliner-secrets
  namespace: mlops
  labels:
    app: gliner-api
type: Opaque
data:
  # These values are base64 encoded
  # Note: In production, use a secrets management service like AWS Secrets Manager, Vault, or Azure Key Vault
  API_KEY: "Y2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=" # base64 encoded "change_me_in_production"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  
# Use environment-specific kustomization to apply proper values for each environment